# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Zhang-Ziyong"
repo_name: "paper_update"
show_authors: True
show_links: True
show_badge: True
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "SLAM": 
        filters: ["SLAM", "Visual Odometry"]
    "SFM":
        filters: ["SFM", "Structure from Motion"]
    "Image Matching":
        filters: ["Image Matching", "Keypoint Matching",
                  "Line Segment Detection", "Local Feature Matching"]
    "Obstacle Avoidance":
        filters: ["Obstacle Avoidance", "Collision Avoidance"]
    "Motion Planning":
        filters: ["Motion Planning", "Path Planning", "Trajectory Planning"]
    "Navigation":
        filters: ["Robot Navigation", "Autonomous Navigation", "Visual Navigation"]
    "Sensor Calibration":
        filters: ["Sensor Calibration", "Camera Calibration", "IMU Calibration", "LiDAR Calibration", "Extrinsic Calibration", "Hand-Eye Calibration", "Intrinsic Calibration"]
    "Sensor Undistortion":
        filters: ["Motion Distortion", "Motion Blur", "Undistortion", "Distortion Correction"]

# GitHub organizations to monitor
github_orgs:
    - "hku-mars"
    - "ethz-asl"

github_repos_json_path: './docs/github-repos.json'
